---
language: node_js
node_js:
  - "4.2.2"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set registry http://registry.npmjs.org/
  - npm config set spin false
  - npm install -g bower
  - git config user.name 'Leooo'
  - bower --version
  - npm install phantomjs-prebuilt@2
  - phantomjs --version

install:
  - npm install

script:
  - ember test
